-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES
create table public.profiles (
  id uuid references auth.users not null primary key,
  created_at timestamptz default now(),
  joined_at timestamptz,
  activation_date timestamptz,
  activated boolean default false,
  home_postcode text,
  last_seen_at timestamptz,
  last_known_tile text
);

-- Enable RLS
alter table public.profiles enable row level security;

-- Policies
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- PINGS
create table public.pings (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id),
  created_at timestamptz default now(),
  postcode text,
  tile text,
  source text
);

-- Enable RLS
alter table public.pings enable row level security;

create policy "Users can insert own pings."
  on pings for insert
  with check ( auth.uid() = profile_id );

create policy "Pings are viewable by everyone (aggregated)."
  on pings for select
  using ( true );

-- NETWORK STATS VIEW
create or replace view network_stats as
select
  count(distinct profile_id) as total_participants,
  count(distinct case when created_at > now() - interval '24 hours' then profile_id end) as active_last_24h
from pings
where postcode = '1010';
